### ISSUE TITLE
Izuzetak pri prikazu aktivnosti vozača

### ISSUE THREAD

**Issue by admirah** [SoftverInzenjeringETFSA/SI2015Tim7#31]
Komponenta:
Vozni Park

commit ID:
03493ed

Opis problema:
Klikom na dugme koje treba da prikaže aktivnosti vozača ako je vozač odabran desi se izuzetak

Koraci za reproduciranje problema:
1. Login kao sef
2. Kliknuti na Pregled vozača
3. Pritisnuti na button Pregled aktivnosti nakon što je odabran vozač

Dobijeni rezultat:
Unhandled exception

Screenshot:
http://prnt.sc/b4srnu

Očekivani rezultat:
Prikaz aktivnosti vozača

**Comment by anogo1** [comment]
mozes li pocetak, prvih 5-6 linija exceptiona uslikati, pošto uopšte ne dobijam exception kada pratim ove korake

**Comment by admirah** [comment]
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
    at vozniPark.Controller.PregledVoznjiController.ucitajVoznjeZaVozaca(PregledVoznjiController.java:46)
    at vozniPark.View.PrikazAktivnostiVozaca.initialize(PrikazAktivnostiVozaca.java:71)
    at vozniPark.View.PrikazAktivnostiVozaca.<init>(PrikazAktivnostiVozaca.java:48)
    at vozniPark.View.PregledVozaca$4.actionPerformed(PregledVozaca.java:103)
    at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
    at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
    at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
    at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
    at java.awt.Component.processMouseEvent(Unknown Source)
    at javax.swing.JComponent.processMouseEvent(Unknown Source)
    at java.awt.Component.processEvent(Unknown Source)
    at java.awt.Container.processEvent(Unknown Source)
    at java.awt.Component.dispatchEventImpl(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Window.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$500(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by anogo1** [comment]
ispravljen zajedno sa issue #30 
(u istom commitu)
